package triatlon.network.jsonprotocol;


public enum RequestType {
    LOGIN, LOGOUT, REGISTER, GET_LOGGED_REFREES, ADD_RESULT, GET_RESULTS_FOR_PROBA,
    GET_ALL_RESULTS, GET_ALL_PARTICIPANTS, CALCULATE_TOTAL_SCORE, GET_ALL_PROBE,
    FIND_ARBITRU, GET_PROBA_FOR_ARBITRU
}