namespace TriatlonNetworking.jsonprotocol;

public enum ResponseType {
    OK, ERROR, GET_LOGGED_REFREES, REFREE_LOGGED_IN, REFREE_LOGGED_OUT,
    GET_ALL_RESULTS, REZULTAT_ADDED, GET_ALL_PARTICIPANTS, GET_RESULTS_FOR_PROBA,
    GET_PROBA_FOR_ARBITRU, GET_ALL_PROBE
}